name: ci

on: 
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('docs/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-          
      - uses: actions/checkout@v3
      - name: download vidwo
        id: download
        shell: pwsh
        run: |
          docker pull testr2/zoomrec


          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
      
      - uses: actions/upload-artifact@v3
        with:
          name: img
          path: output/images/*
      

      - name: Release
        uses: softprops/action-gh-release@v1
        continue-on-error: false
        with:
          name: ${{ steps.download.outputs.release_name }}
          tag_name: ${{ github.run_id }}
          #body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: |
            output/images/*

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
